# Generated by Django 2.2.5 on 2019-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191011_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_confirm',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
