# Generated by Django 2.2.5 on 2019-10-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20191015_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('remain', models.IntegerField()),
                ('instruction', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=50)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Shop')),
            ],
        ),
    ]
