# Generated by Django 2.2.5 on 2019-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_goods_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='remain',
            field=models.IntegerField(default=0),
        ),
    ]
