# Generated by Django 2.2.5 on 2019-10-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('sales', models.CharField(max_length=10)),
                ('remain', models.IntegerField(default=0)),
                ('instruction', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=50)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Shop')),
            ],
        ),
    ]
