# Generated by Django 2.2.5 on 2019-10-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
