# Generated by Django 2.2.5 on 2019-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instruction',
            field=models.CharField(default='', max_length=100),
        ),
    ]
