# Generated by Django 2.2.6 on 2019-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_shop_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='shopping_cart',
            field=models.CharField(default='null', max_length=25),
        ),
    ]
