# Generated by Django 2.2.6 on 2019-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_profile_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='shopping_cart',
            field=models.IntegerField(default=0),
        ),
    ]
