# Generated by Django 2.2.5 on 2019-10-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191018_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture',
        ),
    ]
