# Generated by Django 2.0.5 on 2019-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
