# Generated by Django 2.2.6 on 2019-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
