# Generated by Django 2.2.6 on 2019-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goods_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='modify_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
