# Generated by Django 2.2.6 on 2019-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
