# Generated by Django 2.2.6 on 2019-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
